title: Making an app to app voice call
description: You make a voice call from an iOS app to another iOS app
products:
  - client-sdk

introduction:
  title: Introduction to this task
  description: This task shows you how to use make a phone call from an iOS application to another iOS application using the iOS Client SDK and Swift.
  content: |
    # Introduction
    In this tutorial, you will learn how to create an iOS application using Swift and the Nexmo iOS Client SDK, and then write the code to make an app to app call.

    Two parts are needed to achieve this:

    * An iOS application that will make the voice call using the Client SDK.
    * A publicly accessible URL that serves instructions on how to handle the call. To accomplish this, you will create a webhook server using <a href="https://nodejs.org/en/" target="_blank">Node.js</a>, <a href="https://expressjs.com/" target="_blank">Express</a> and <a href="https://github.com/localtunnel/localtunnel" target="_blank">localtunnel</a>.

    ### Completed project
    If you would like to follow along without building the app yourself, the completed project is available on [Github](https://github.com/nexmo-community/client-sdk-tutorials) -  please see the [app-to-app-swift](https://github.com/nexmo-community/client-sdk-tutorials/tree/main/app-to-app-swift) folder.

    *This tutorial uses NexmoClient version 3.0.0 and Swift 5*

prerequisites:
  - create-nexmo-account
  - install-nodejs
  - install-vonage-cli-beta
  - install-vonage-cli-plugins
  - install-xcode

tasks:
  - client-sdk/app-to-app/create-webhook-server
  - client-sdk/app-to-app/create-application
  - client-sdk/create-users-alice-and-bob-beta
  - client-sdk/generate-jwts-alice-and-bob-beta
  - client-sdk/app-to-app/create-project
  - client-sdk/app-to-app/add-permissions
  - client-sdk/app-to-app/main-screen
  - client-sdk/app-to-app/create-model
  - client-sdk/app-to-app/client
  - client-sdk/app-to-app/call-ui
  - client-sdk/app-to-app/receive-call
  - client-sdk/app-to-app/place-call

conclusion:
  title: What's next?
  description: What else can you do with the Client SDK?
  content: |

    # What's next?

    The complete version of the project you just built is available on [Github](https://github.com/nexmo-community/client-sdk-tutorials) -  please see the [app-to-app-swift](https://github.com/nexmo-community/client-sdk-tutorials/tree/main/app-to-app-swift) folder.

    You can do a lot more with the Client SDK. For an summary, please see the [Client SDK Overview](/client-sdk/overview) or review the [iOS Client SDK documentation](/client-sdk/sdk-documentation/ios).

    We want to hear what ideas you have in mind! Contact us at [devrel@vonage.com](mailto:devrel@vonage.com)
