title: Receiving a phone call in-app
description: You receive a call from a phone to your app
products:
  - client-sdk

introduction:
  title: Introduction to this task
  description: This task shows you how to handle an inbound call into your web app using the iOS Client SDK.
  content: |
    # Introduction
    In this tutorial, you will learn how to create an iOS application using Objective-C and the Nexmo iOS Client SDK, and then write the code to receive a phone call to your iOS app from a phone.

    Two parts are needed to achieve this:

    * An iOS application that will receive the voice call using the Client SDK.
    * A publicly accessible URL that serves instructions on how to handle the call. To accomplish this, you will create a webhook server using <a href="https://nodejs.org/en/" target="_blank">Node.js</a>, <a href="https://expressjs.com/" target="_blank">Express</a> and <a href="https://github.com/localtunnel/localtunnel" target="_blank">localtunnel</a>.

    ### Completed project
    If you would like to follow along without building the app yourself, the completed project is available on [Github](https://github.com/nexmo-community/client-sdk-tutorials) -  please see the [phone-to-app-objc](https://github.com/nexmo-community/client-sdk-tutorials/tree/main/phone-to-app-objc) folder.

    *This tutorial uses NexmoClient version 3.0.0*

prerequisites:
- create-vonage-account
- install-nodejs
- install-vonage-cli
- install-vonage-cli-plugins
- install-xcode

tasks:
- client-sdk/phone-to-app/create-webhook-server
- client-sdk/phone-to-app/create-application
- buy-vonage-number
- link-vonage-number
- client-sdk/create-user-alice-vonage
- client-sdk/generate-jwt-alice-vonage
- client-sdk/phone-to-app/create-project
- client-sdk/phone-to-app/add-permissions
- client-sdk/phone-to-app/main-screen
- client-sdk/phone-to-app/client
- client-sdk/phone-to-app/receive-call


conclusion:
  title: What's next?
  description: What else can you do with the Client SDK?
  content: |

    # What's next?

    The complete version of the project you just built is available on [Github](https://github.com/nexmo-community/client-sdk-tutorials) -  please see the [phone-to-app-objc](https://github.com/nexmo-community/client-sdk-tutorials/tree/main/phone-to-app-objc) folder.

    You can do a lot more with the Client SDK. For an summary, please see the [Client SDK Overview](/client-sdk/overview) or review the [iOS Client SDK documentation](/client-sdk/sdk-documentation/ios).

    We want to hear what ideas you have in mind! Contact us at [devrel@vonage.com](mailto:devrel@vonage.com)

